"""Phase 2 — Self-attribution experiment.

For each model M and each prompt P:
  - Take model M's response (response_A)
  - Take a random adversary model's response (response_B)
  - Randomize A/B position
  - Ask model M: which response is yours?
  - Measure accuracy vs 50% baseline

Saves to data/results/attribution_results.csv (resumable).
"""

from __future__ import annotations

import os
import random
import time
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from tqdm import tqdm

load_dotenv()

ROOT = Path(__file__).resolve().parents[1]
GEN_DIR = ROOT / "data" / "generated"
RESULTS_DIR = ROOT / "data" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
OUT_PATH = RESULTS_DIR / "attribution_results.csv"

SLEEP_BETWEEN = 1.6
RANDOM_SEED = 42

ATTRIBUTION_SYSTEM = (
    "You are participating in an experiment. "
    "Answer with only 'A' or 'B', nothing else. No explanation."
)

ATTRIBUTION_TEMPLATE = """You will see two responses to the same question.
One was generated by you. The other was generated by a different AI model.

Question: {prompt}

Response A:
{response_a}

Response B:
{response_b}

Which response did you generate? Answer with only 'A' or 'B'."""


def ask_attribution(client: OpenAI, model: str, prompt: str, response_a: str, response_b: str) -> str:
    """Ask model to identify its own response. Returns 'A', 'B', or 'invalid'."""
    user_msg = ATTRIBUTION_TEMPLATE.format(
        prompt=prompt,
        response_a=response_a,
        response_b=response_b,
    )
    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": ATTRIBUTION_SYSTEM},
                {"role": "user", "content": user_msg},
            ],
            temperature=0,
            max_tokens=5,
        )
        answer = resp.choices[0].message.content.strip().upper()
        if answer in ("A", "B"):
            return answer
        # Try to extract A or B from longer response
        for char in answer:
            if char in ("A", "B"):
                return char
        return "invalid"
    except Exception as e:
        print(f"    [error] {e}")
        return "error"


def load_all_responses() -> pd.DataFrame:
    """Load all generated responses into a single DataFrame."""
    frames = []
    for f in GEN_DIR.glob("*.csv"):
        frames.append(pd.read_csv(f))
    if not frames:
        raise FileNotFoundError("No generated responses found. Run 01_generate.py first.")
    return pd.concat(frames, ignore_index=True)


def main() -> None:
    api_key = os.environ.get("NVIDIA_API_KEY")
    if not api_key:
        raise ValueError("Set NVIDIA_API_KEY in .env")

    client = OpenAI(
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=api_key,
    )

    rng = random.Random(RANDOM_SEED)
    df = load_all_responses()
    models = df["model"].unique().tolist()
    print(f"Loaded {len(df)} responses across {len(models)} models")

    # Load existing results to resume
    if OUT_PATH.exists():
        existing = pd.read_csv(OUT_PATH)
        done_keys = set(zip(existing["model"], existing["prompt_id"], existing["adversary_model"]))
    else:
        existing = pd.DataFrame()
        done_keys = set()

    rows = existing.to_dict("records") if not existing.empty else []

    for model in models:
        model_df = df[df["model"] == model]
        adversaries = [m for m in models if m != model]
        if not adversaries:
            continue

        print(f"\n[{model}] {len(model_df)} prompts × {len(adversaries)} adversaries")

        for _, row in tqdm(model_df.iterrows(), total=len(model_df), desc=model.split("/")[-1][:20]):
            prompt_id = row["prompt_id"]
            # Pick one random adversary per prompt
            adversary = rng.choice(adversaries)

            key = (model, prompt_id, adversary)
            if key in done_keys:
                continue

            adv_row = df[(df["model"] == adversary) & (df["prompt_id"] == prompt_id)]
            if adv_row.empty:
                continue
            adv_response = adv_row.iloc[0]["response"]

            # Randomize position (A/B) to avoid position bias
            own_is_a = rng.random() < 0.5
            if own_is_a:
                response_a, response_b = row["response"], adv_response
                correct_answer = "A"
            else:
                response_a, response_b = adv_response, row["response"]
                correct_answer = "B"

            model_answer = ask_attribution(
                client, model, row["prompt"], response_a, response_b
            )

            result = {
                "model": model,
                "prompt_id": prompt_id,
                "category": row["category"],
                "adversary_model": adversary,
                "own_is_a": own_is_a,
                "correct_answer": correct_answer,
                "model_answer": model_answer,
                "correct": model_answer == correct_answer,
            }
            rows.append(result)
            done_keys.add(key)

            pd.DataFrame(rows).to_csv(OUT_PATH, index=False)
            time.sleep(SLEEP_BETWEEN)

    print(f"\nDone. Results saved to {OUT_PATH}")


if __name__ == "__main__":
    main()
